### ISSUE TITLE
Error single positional indexer is out-of-bounds

### ISSUE THREAD

**Issue by dcoia740** [msbentley/psa_utils#3]
Searching the PSA with query: 
dos_v1=psa.query("select granule_uid, time_min, time_max from epn_core where granule_uid like '%frd_raw_sc%::1.%'")  

Results in error: 
`
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [63], in <cell line: 1>()
----> 1 dos_v1=psa.query("select granule_uid, time_min, time_max from epn_core where granule_uid like '%frd_raw_sc%::1.%'")

File ~/opt/anaconda3/envs/test/lib/python3.8/site-packages/psa_utils-0.2.3-py3.8.egg/psa_utils/tap.py:56, in PsaTap.query(self, q, sync, dropna, verbose, job_wait_cycles, job_wait_time)
     53     for col, dtype in data.dtypes.items():
     54         if dtype == np.object:
     55             # check if we really have bytes here or a string
---> 56             if not isinstance(data[col].iloc[0], str):
     57                 data[col] = data[col].str.decode('utf-8')
     59 else:

File ~/opt/anaconda3/envs/test/lib/python3.8/site-packages/pandas-1.4.2-py3.8-macosx-10.9-x86_64.egg/pandas/core/indexing.py:967, in _LocationIndexer.__getitem__(self, key)
    964 axis = self.axis or 0
    966 maybe_callable = com.apply_if_callable(key, self.obj)
--> 967 return self._getitem_axis(maybe_callable, axis=axis)

File ~/opt/anaconda3/envs/test/lib/python3.8/site-packages/pandas-1.4.2-py3.8-macosx-10.9-x86_64.egg/pandas/core/indexing.py:1520, in _iLocIndexer._getitem_axis(self, key, axis)
   1517     raise TypeError("Cannot index by location index with a non-integer key")
   1519 # validate the location
-> 1520 self._validate_integer(key, axis)
   1522 return self.obj._ixs(key, axis=axis)

File ~/opt/anaconda3/envs/test/lib/python3.8/site-packages/pandas-1.4.2-py3.8-macosx-10.9-x86_64.egg/pandas/core/indexing.py:1452, in _iLocIndexer._validate_integer(self, key, axis)
   1450 len_axis = len(self.obj._get_axis(axis))
   1451 if key >= len_axis or key < -len_axis:
-> 1452     raise IndexError("single positional indexer is out-of-bounds")

IndexError: single positional indexer is out-of-bounds
`

**Comment by msbentley** [comment]
Thanks @dcoia740 - hopefully this is fixed in https://github.com/msbentley/psa_utils/commit/09e2417d27a66fdf618d26cfa5a741666621e961 and should be in the next release
